version: '3.7'
services:
  app:
    image: lilkhalil/listenloud
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=listenloud